ci:
    autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
      - id: check-merge-conflict
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.1b3
    hooks:
      - id: hadolint
        args: [
          --ignore, DL3025,
          --ignore, DL3018,
          --ignore, DL3008,
          --ignore, DL3003,
          --ignore, DL3013,
          --ignore, SC1091,
        ]
        files: ^dockerfiles/.*
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
