ARG PYTHON_VERSION="3.11"
ARG SSL_ARGS=""

from python:${PYTHON_VERSION}-slim-buster

ENV PROXYSTORE_SSL_ARGS $SSL_ARGS

RUN apt-get update \
  && apt-get install -y --no-install-recommends gcc g++ \
  && apt-get clean autoclean \
  && rm -rf /var/lib/apt/lists/*

RUN pip install --pre "proxystore[endpoints]"

EXPOSE 8765

CMD [ "sh", "-c", "proxystore-relay --port 8765 --log-dir ./logs --log-level DEBUG $PROXYSTORE_SSL_ARGS" ]
