ARG PYTHON_VERSION="3.11"

from python:${PYTHON_VERSION}-slim-buster

ARG CONFIG="/data/config.toml"
ARG PORT=8700

ENV CONFIG=${CONFIG}

RUN pip install --no-cache-dir "proxystore[endpoints]"

EXPOSE $PORT

ENTRYPOINT [ "/bin/sh", "-c" ]
CMD [ "proxystore-relay --config ${CONFIG}" ]
