name: check

on:
  pull_request:
    branches: [main]
    paths: [dockerfiles/**]

jobs:
  verify-build:
    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile-dim
            image_name: proxystore-dim
          - dockerfile: Dockerfile-relay
            image_name: proxystore-relay
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if Dockerfile changed
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            addedOrModified:
              - added|modified: '**'
            dockerfile: ['dockerfiles/${{ matrix.dockerfile }}']

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: steps.filter.outputs.dockerfile == 'true'

      - name: Build Docker image
        uses: docker/build-push-action@v3
        if: steps.filter.outputs.dockerfile == 'true'
        with:
          context: "{{defaultContext}}:dockerfiles"
          file: ${{ matrix.dockerfile }}
          push: false
