name: publish

on:
  schedule:
    # Runs on the 1st and 15th of every month at 2am CST (7am UTC)
    - cron: '00 7 1,15 * *'
  push:
    branches: [main]
    paths: [dockerfiles/**]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-publish:
    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile-dim
            image_name: proxystore-dim
            description: Distributed in-memory store testing image.
          - dockerfile: Dockerfile-relay
            image_name: proxystore-relay
            description: Relay (signaling) server runner.
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if Dockerfile changed
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            addedOrModified:
              - added|modified: '**'
            dockerfile: ['dockerfiles/${{ matrix.dockerfile }}']

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: steps.filter.outputs.dockerfile == 'true' || github.event_name == 'schedule'

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        if: steps.filter.outputs.dockerfile == 'true' || github.event_name == 'schedule'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        if: steps.filter.outputs.dockerfile == 'true' || github.event_name == 'schedule'
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.image_name }}
          labels: |
            org.opencontainers.image.description=${{ matrix.description }}
          tags: |
            type=raw,value=latest
            type=raw,value=nightly
            type=raw,value={{date 'YYYY-MM-DD'}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        if: steps.filter.outputs.dockerfile == 'true' || github.event_name == 'schedule'
        with:
          context: "{{defaultContext}}:dockerfiles"
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
